import { randomBytes } from "node:crypto";
import type { Client } from "pg";

/**
 * Judgment Day round 4: the destructive live-RLS suites used to apply
 * migrations and `DROP TABLE ... CASCADE` directly against the `public`
 * schema of `LIVE_TEST_DATABASE_URL`. `assertThrowawayDatabase` only proves
 * the *database* is disposable — it says nothing about the schema inside
 * it, so a throwaway database that happens to carry other tables in
 * `public` (or a bug in the guard itself) could still destroy real data.
 * This module isolates each suite's destructive work inside its own
 * uniquely-named schema, created at the start of a run and dropped with
 * `DROP SCHEMA ... CASCADE` at the end — `public` is never touched.
 *
 * `migrations/0000_init.sql`'s foreign keys are generated by drizzle-kit as
 * fully-qualified `REFERENCES "public"."<table>"(...)`; every unqualified
 * identifier (`CREATE TABLE "brokers"`, `ALTER TABLE brokers ...`) resolves
 * via `search_path` instead. `rewriteSchemaQualification` rewrites the
 * hardcoded `"public".` qualifier to the throwaway schema, and callers pair
 * that with a `search_path` set on every connection (via `ALTER ROLE ...
 * SET search_path`, which applies to all of a role's future connections
 * without needing to repeat the `SET` per `Client`) so the unqualified
 * statements land in the same schema.
 */

/** Generates a schema name that cannot collide with a real, hand-authored schema. */
export function randomThrowawaySchemaName(): string {
  return `rls_probe_${randomBytes(6).toString("hex")}`;
}

/**
 * Rewrites drizzle-kit's hardcoded `"public".` FK qualifier to target
 * `schema` instead. Asserts that every migration carrying a `REFERENCES`
 * clause also carries at least one `"public".`-qualified match to rewrite
 * (0000_init.sql today; a migration with no FKs at all, e.g.
 * 0002_rls_policies.sql, legitimately has neither and is not flagged). A
 * migration with `REFERENCES` but zero `"public".` matches means a future
 * drizzle-kit version changed how it quotes the FK target, which would
 * otherwise make this rewrite a silent no-op — the migration would still
 * apply, but its FKs would still target `public` instead of the throwaway
 * schema. Fail loudly instead of passing by accident.
 */
export function rewriteSchemaQualification(sql: string, schema: string): string {
  const referencesCount = (sql.match(/REFERENCES\s/g) ?? []).length;
  const qualifiedCount = sql.split('"public".').length - 1;
  if (referencesCount > 0 && qualifiedCount === 0) {
    throw new Error(
      `rewriteSchemaQualification found ${referencesCount} "REFERENCES" clause(s) but no ` +
        '`"public".` qualifiers to rewrite — drizzle-kit\'s FK-quoting format likely changed. ' +
        "Refusing to silently no-op, since that would leave this migration's FKs targeting " +
        "`public` instead of the throwaway schema.",
    );
  }
  return sql.replaceAll('"public".', `"${schema}".`);
}

/** Creates the throwaway schema. Callers are responsible for dropping it in `afterAll`, gated on `safeToMutate`. */
export async function createThrowawaySchema(admin: Client, schema: string): Promise<void> {
  await admin.query(`CREATE SCHEMA "${schema}"`);
}

/** Drops the throwaway schema and everything in it. Never touches `public`. */
export async function dropThrowawaySchema(admin: Client, schema: string): Promise<void> {
  await admin.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
}

/**
 * Judgment Day round 5 (WARNING): a hard process kill (Ctrl-C, OOM, CI
 * `cancel-in-progress`) skips `afterAll` entirely, so a crashed run's
 * `rls_probe_<random>` schema is never dropped. Left alone across many local
 * re-runs, these accumulate in a long-lived developer database. This sweep
 * is scoped to the distinctive `rls_probe_` prefix `randomThrowawaySchemaName`
 * always generates, so it can never match a hand-authored schema — safe to
 * run unconditionally once the caller has already confirmed (via
 * `assertThrowawayDatabase`) that the target database itself is disposable.
 */
export async function sweepOrphanedThrowawaySchemas(admin: Client): Promise<void> {
  const result = await admin.query<{ nspname: string }>(
    `SELECT nspname FROM pg_namespace WHERE nspname LIKE 'rls\\_probe\\_%' ESCAPE '\\'`,
  );
  for (const row of result.rows) {
    await admin.query(`DROP SCHEMA IF EXISTS "${row.nspname}" CASCADE`);
  }
}
