import { randomBytes } from "node:crypto";
import type { Client } from "pg";

/**
 * Judgment Day round 4: the destructive live-RLS suites used to apply
 * migrations and `DROP TABLE ... CASCADE` directly against the `public`
 * schema of `LIVE_TEST_DATABASE_URL`. `assertThrowawayDatabase` only proves
 * the *database* is disposable — it says nothing about the schema inside
 * it, so a throwaway database that happens to carry other tables in
 * `public` (or a bug in the guard itself) could still destroy real data.
 * This module isolates each suite's destructive work inside its own
 * uniquely-named schema, created at the start of a run and dropped with
 * `DROP SCHEMA ... CASCADE` at the end — `public` is never touched.
 *
 * `migrations/0000_init.sql`'s foreign keys are generated by drizzle-kit as
 * fully-qualified `REFERENCES "public"."<table>"(...)`; every unqualified
 * identifier (`CREATE TABLE "brokers"`, `ALTER TABLE brokers ...`) resolves
 * via `search_path` instead. `rewriteSchemaQualification` rewrites the
 * hardcoded `"public".` qualifier to the throwaway schema, and callers pair
 * that with a `search_path` set on every connection (via `ALTER ROLE ...
 * SET search_path`, which applies to all of a role's future connections
 * without needing to repeat the `SET` per `Client`) so the unqualified
 * statements land in the same schema.
 */

/** Generates a schema name that cannot collide with a real, hand-authored schema. */
export function randomThrowawaySchemaName(): string {
  return `rls_probe_${randomBytes(6).toString("hex")}`;
}

/** Rewrites drizzle-kit's hardcoded `"public".` FK qualifier to target `schema` instead. */
export function rewriteSchemaQualification(sql: string, schema: string): string {
  return sql.replaceAll('"public".', `"${schema}".`);
}

/** Creates the throwaway schema. Callers are responsible for dropping it in `afterAll`, gated on `safeToMutate`. */
export async function createThrowawaySchema(admin: Client, schema: string): Promise<void> {
  await admin.query(`CREATE SCHEMA "${schema}"`);
}

/** Drops the throwaway schema and everything in it. Never touches `public`. */
export async function dropThrowawaySchema(admin: Client, schema: string): Promise<void> {
  await admin.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
}
